flowchart TD
    NT[Người thuê]
    CN[Chủ nhà]
    HTTB[Hệ thống thông báo]

    %% Processes
    P31[Gửi yêu cầu đặt lịch xem]
    P32[Kiểm tra trùng lịch]
    P33[Duyệt / Từ chối lịch xem]
    P34[Cập nhật trạng thái phòng]
    P35[Lưu lịch sử xem phòng]
    P36[Gửi thông báo / nhắc nhở]

    %% Data Stores
    DS1[DB Phòng]
    DS4[DB Lịch xem phòng]
    DS7[DB Thông báo]
    DS8[DB Lịch sử xem phòng]

    %% Flows
    NT --> P31
    P31 --> P32
    P32 --> DS4
    P32 --> P33

    CN --> P33
    P33 --> CN

    P33 --> P34
    P34 --> DS1

    P33 --> P35
    P35 --> DS8

    P33 --> P36
    P36 --> DS7
    DS7 --> HTTB
    HTTB --> NT
    HTTB --> CN
