flowchart TD
    ET1[Chủ nhà]

    %% Processes
    P211[Quản lý thông tin chủ nhà]
    P212[Quản lý danh sách phòng]
    P213[Upload dữ liệu phòng hàng loạt]
    P214[Theo dõi lịch sử tin đăng]
    P215[Tự động cập nhật trạng thái phòng]

    %% Data Stores
    DS2[DB Chủ nhà]
    DS1[DB Phòng]
    DS5[DB Tin đăng]

    %% Flows
    ET1 --> P211
    P211 --> DS2

    ET1 --> P212
    P212 --> DS1

    ET1 --> P213
    P213 --> DS1
    P213 --> DS5

    ET1 --> P214
    P214 --> DS5

    P215 --> DS1
    DS1 --> ET1
    DS5 --> ET1
