flowchart TD
    ET1[Chủ nhà / Quản trị hệ thống] --> P121[Quản lý danh sách tiện nghi chuẩn]
    P121 --> DS1a[DB Tiện nghi]
    
    ET1 --> P122[Liên kết tiện nghi với phòng]
    P122 --> DS1a
    P122 --> DS1[DB Phòng]
    
    ET1 --> P123[Mở rộng tiện nghi theo thực tế]
    P123 --> DS1a
    
    DS1 --> ET1
    DS1a --> ET1
